server:
  # URI is the endpoint that the client connects to
  # eg. localhost, 127.0.0.1, wowdrel.mydomain.com (Config needed)
  URI: "wowdrel.alepablog.com"
  Port: 8080
  WordRotateInterval: 24
  ReadTimeout: 10
  WriteTimeout: 10

database:
  Host: localhost
  Port: 27017
  User: CHANGEME
  Password: CHANGEME
  DBName: wowdrel9000
  DBTimeout: 5
